### ISSUE TITLE
Support other plugin

### ISSUE THREAD

**Issue by HuynhDucPhu** [SamB440/RPGRegions#1]
Can you support:
+ Experience SkillAPI
~~+ 1.8 to 1.12 version~~ - edit: done
:D :D i love this plugin very much

**Comment by SamB440** [comment]
1.8 support should be easy enough, I'll just need to disable the sounds upon discovery. What do you want me to support in SkillAPI?

**Comment by SamB440** [comment]
Closed due to lack of response. Additionally, the plugin you are asking me to support is premium. Feel free to open a new ticket.
