### ISSUE TITLE
Reward for Visit again again again after logout and login (You can close this)

### ISSUE THREAD

**Issue by NevendyND** [SamB440/RPGRegions#2]
Soo i try to explain
I have a Region.
When a User logout on this region and login again he get the reward.
when he while this he got more and more reward.

Its no Ontime.

**Comment by NevendyND** [comment]
ok nvm...

i think it was a bug of myself

now the bug is gone o.o

I think it happens when i delete the: Discoveries.txt on Server Online.

so nvm it's no bug :)

**Comment by SamB440** [comment]
Yes, discoveries.txt is used to store data unless you use MySQL (which is coming soon).
